#!/bin/bash
#
# blog      Startup script for the blog application
#
# chkconfig: 345 89 11
# description: Kubosch Blog

app=blog
port=3002
pidfile=/u/apps/$app/shared/log/mongrel.pid

# See how we were called.
case "$1" in
  start)
        mongrel_rails start -p $port -e production -c /u/apps/$app/current -d 1>/u/apps/$app/shared/log/stdout.log 2>/u/apps/$app/shared/log/stderr.log
        ;;
  stop)
        mongrel_rails stop -c /u/apps/$app/current
        rm -f $pidfile
        ;;
  restart)
        mongrel_rails restart -c /u/apps/$app/current
        ;;
  status)
        ps -ef | grep $app
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart|status}"
        exit 1
esac

exit 0
