# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "blog_entries", :force => true do |t|
    t.column "datetime", :datetime, :null => false
    t.column "title", :string, :limit => 64, :default => "", :null => false
    t.column "text", :text, :default => "", :null => false
    t.column "blog_id", :integer, :default => 1, :null => false
  end

  create_table "blogs", :force => true do |t|
    t.column "title", :string, :limit => 64, :default => "", :null => false
  end

  create_table "images", :force => true do |t|
    t.column "blog_entry_id", :integer
    t.column "picture_data", :binary
    t.column "picture_content_type", :string, :limit => 100
  end

  create_table "users", :force => true do |t|
    t.column "salted_password", :string, :limit => 40, :default => "", :null => false
    t.column "email", :string, :limit => 60, :default => "", :null => false
    t.column "first_name", :string, :limit => 40
    t.column "last_name", :string, :limit => 40
    t.column "salt", :string, :limit => 40, :default => "", :null => false
    t.column "verified", :integer, :default => 0
    t.column "role", :string, :limit => 40
    t.column "security_token", :string, :limit => 40
    t.column "token_expiry", :datetime
    t.column "deleted", :integer, :default => 0
    t.column "delete_after", :datetime
  end

end
